spring:
  application:
    name: StudentCanteen
  profiles:
    active: '@build.profile.id@'
  thymeleaf:
    cache: false


jwt:
  secret: 19ADSKJDGKJ12983JKDFHAKAS  #JWT密钥
  expiration: 864000000              #JWT过期时间（1000天）
